### ISSUE TITLE
Configurable statement_indentation rule

### ISSUE THREAD

**Issue by theeldarka** [laravel/pint#167]
I've updated Laravel Pint from 1.7 to 1.8, and now my lines with comments are moving.
I can disable this rule, but it will allow my co-workers do mistakes. PhpStorm doesn't follow this rule when I press the shortcut to comment lines.
![Screenshot 2023-04-05 at 13 50 50](https://user-images.githubusercontent.com/39298674/230047115-1043ccf6-b38c-4ce1-a3ec-4ccd47c6ce5d.png)

on the 1.7 version there wasn't this problem

**Comment by theeldarka** [comment]
I rollback pint's changes, and downgrade to 1.7 version, run pint again, and it gave "success" result without changes

**Comment by Jubeki** [comment]
@theeldarka This is not a problem with Laravel Pint.

Because the PSR-12 ruleset is not decided here but in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer

statement_indentation rule was added to PSR-2 which is also used in PSR-12:
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/4885/files#diff-363628d5d69ccafd96d2e0af8e53953f65ced7cc64fd9c5dc63631977e5abfa6R58

**Comment by driesvints** [comment]
@nunomaduro @Jubeki this does seem problematic to me? Afaik comments always start at char 0.

**Comment by Jubeki** [comment]
@driesvints Well yeah, its kind of a bug of the statement_indentation rule.
(VS Code places the comment correctly aligned with the code, were PhpStorm places it as the beginning of the line it seems)

What I meant:
The laravel preset has the rule disabled.
Where as PSR-12 (via PSR-2) has it enabled. So I think the right place to report it would be PHP-CS-Fixer instead of here.
