### ISSUE TITLE
[Volt] Format blade files

### ISSUE THREAD

**Issue by robsontenorio** [laravel/pint#217]
Considering increasing Volt popularity, do you guys reconsidered supporting blade files? Or not plans yet?

**Comment by driesvints** [comment]
This would be amazing but unfortunately there isn't good tooling at this point. If someone could point out proper tooling for formatting Blade files in the same paradigm as Pint then we could have a look. Things like Prettier are unfortunately not an option since we can't bundle it into the binary.

**Comment by chrillep** [comment]
Totally agree this would be awesome. The problem is there still isn’t **good PHP‑native Blade formatting tooling** that fits Pint’s “single binary, no Node” model.

Right now the options are:

- **Blade → PHP lint/analysis** (not formatting):  
  https://github.com/Magentron/laravel-blade-lint  
  https://github.com/bladestan/bladestan  

- **Prettier + Blade plugin** (works but not usable in Pint):  
  https://github.com/laravel/pint/pull/256  

The closest formatter architecture in PHP is **Twig‑CS‑Fixer**, but it’s Twig‑specific so you’d have to rewrite the parser + rules for Blade:  
https://github.com/VincentLanglet/Twig-CS-Fixer  

A very promising missing piece is **Stillat/blade-parser** — it’s a real Blade parser/AST made for tooling, and could be the base for a formatter:  
https://github.com/Stillat/blade-parser  

There’s also **tailwind-cs-fixer** (PHP, class sorting in HTML/Twig), maybe useful for Tailwind ordering in Blade:  
https://github.com/IQ2i/tailwind-cs-fixer  

So yeah… no drop‑in formatter today, but **a PHP‑native Blade formatter is totally doable** if someone builds a rule engine on top of blade‑parser. If anyone knows an existing PHP formatter like that, that’s the missing piece.
